apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
      - name: challenge
        image: 1337docker101/nginx
        resources:
          limits:
            memory: 200Mi
            cpu: 1.5
          requests:
            memory: 100Mi
            cpu: 1
        ports:
        - containerPort: 80