apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 1337docker101/nginx
        resources:
          limits:
            memory: "200Mi"
            cpu: 0.05
          requests:
            memory: "100Mi"
            cpu: 0.02
        ports:
        - containerPort: 80